### ISSUE TITLE
Support for windows operating systems

### ISSUE THREAD

**Issue by ryanluker** [AdrianSchneider/httprompt#5]
Currently using the command prompt errors the prompt out before it can load.

``` C:\dev\httprompt>httprompt
path.js:146
      throw new TypeError('Arguments to path.resolve must be strings');
      ^
TypeError: Arguments to path.resolve must be strings
    at Object.win32.resolve (path.js:146:13)
    at Object.<anonymous> (C:\Users\ryanl\AppData\Roaming\npm\node_modules\httprompt\bin\httprompt:18:45)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

```

**Comment by AdrianSchneider** [comment]
httprompt needs to load (or create default and load) config before it can do anything. You can pick the location with one with the `-c <filename>` option. It's currently failing trying to use your home directory, because I'm guessing Windows or cywgin? doesn't have `HOME` set in your case.

We could add a fallback to try `HOME`  then `HOMEPATH` (which appears to be present in windows) rather than having it error out.

Let me know if the `-c` option works, and if you can, try setting your `HOME` env manually first:

`HOME=C:\Users\ryanl httprompt`

Both should work to verify this is the problem.
